# Generated by Django 5.1 on 2024-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=100)),
                ('last_reading', models.IntegerField()),
                ('new_reading', models.IntegerField()),
                ('reading_date', models.DateField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
