# Generated by Django 5.1 on 2024-09-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer'),
        ),
    ]
