# Generated by Django 5.1 on 2024-10-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_initial'),
        ('consumer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='consumer.consumer'),
        ),
    ]
