# Generated by Django 5.1 on 2024-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consumer_number', models.CharField(max_length=100, unique=True)),
                ('meter_number', models.CharField(max_length=100, unique=True)),
                ('area_number', models.CharField(max_length=100)),
                ('tariff', models.CharField(choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
