# Generated by Django 5.1 on 2024-10-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDO', '0001_initial'),
        ('consumer', '0004_alter_consumer_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='tariff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDO.tariff'),
        ),
    ]
