# Generated by Django 5.1 on 2024-10-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=10),
        ),
    ]
